python cal_pesq.py reference.wav log\0_without_plc.wav
python cal_pesq.py reference.wav log\0_with_plc_g711.wav
python cal_pesq.py reference.wav log\10_without_plc.wav
python cal_pesq.py reference.wav log\10_with_plc_g711.wav
python cal_pesq.py reference.wav log\20_without_plc.wav
python cal_pesq.py reference.wav log\20_with_plc_g711.wav
python cal_pesq.py reference.wav log\30_without_plc.wav
python cal_pesq.py reference.wav log\30_with_plc_g711.wav
python cal_pesq.py reference.wav log\40_without_plc.wav
python cal_pesq.py reference.wav log\40_with_plc_g711.wav
python cal_pesq.py reference.wav log\50_without_plc.wav
python cal_pesq.py reference.wav log\50_with_plc_g711.wav
python cal_pesq.py reference.wav log\60_without_plc.wav
python cal_pesq.py reference.wav log\60_with_plc_g711.wav
python cal_pesq.py reference.wav log\70_without_plc.wav
python cal_pesq.py reference.wav log\70_with_plc_g711.wav
python cal_pesq.py reference.wav log\80_without_plc.wav
python cal_pesq.py reference.wav log\80_with_plc_g711.wav
python cal_pesq.py reference.wav log\90_without_plc.wav
python cal_pesq.py reference.wav log\90_with_plc_g711.wav
